# upload.py
import os
import pickle
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# === GOOGLE API AYARLARI ===
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
CLIENT_SECRET_FILE = "client_secret.json"
TOKEN_PICKLE = "token.pickle"

def authenticate_youtube():
    """OAuth2 ile kimlik doğrulama yapar."""
    creds = None
    if os.path.exists(TOKEN_PICKLE):
        with open(TOKEN_PICKLE, "rb") as token:
            creds = pickle.load(token)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRET_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(TOKEN_PICKLE, "wb") as token:
            pickle.dump(creds, token)

    return build("youtube", "v3", credentials=creds)

def upload_to_youtube(video_path: str, title: str) -> str:
    """
    Videoyu YouTube'a yükler.
    İlk çalıştırmada tarayıcı açılacak → Google hesabı seçip onayla.
    """
    try:
        youtube = authenticate_youtube()

        # Açıklama
        description = (
            "Automatically generated by AI workflow.\n"
            "Fikir → Senaryo → Ses → Video → Upload\n"
            "GitHub: your-repo-link"
        )

        request_body = {
            "snippet": {
                "title": title[:100],  # YouTube max 100 karakter
                "description": description,
                "tags": ["AI", "automation", "generated"],
                "categoryId": "28"  # Science & Technology
            },
            "status": {
                "privacyStatus": "private"  # Önce private!
            }
        }

        media_file = MediaFileUpload(video_path, chunksize=-1, resumable=True)

        request = youtube.videos().insert(
            part="snippet,status",
            body=request_body,
            media_body=media_file
        )

        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                print(f"Uploaded {int(status.progress() * 100)}%")

        video_id = response["id"]
        return f"✅ YouTube'a yüklendi!\nVideo ID: {video_id}\nBaşlık: {title[:50]}..."

    except Exception as e:
        return f"❌ YouTube yükleme hatası:\n{str(e)}"